version: '3.9'

services:
  inventory-manager:
    image: inventory-manager:1
    container_name: inventory-manager
    hostname: inventory-manager
    ports:
      - "5000:5000"
    volumes:
      - ./:/inventory-manager
    restart: unless-stopped