version: '3.9'

services:
  app:
    build: .
    container_name: flask_inventory_app
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - ./data:/app/data
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: unless-stopped